# Generated by Django 4.0 on 2022-06-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
    ]
