# Generated by Django 4.0.4 on 2022-04-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default='asd'),
            preserve_default=False,
        ),
    ]
